### ISSUE TITLE
Males are assigned futa trait at startup

### ISSUE THREAD

**Issue by Triskelia** [cherisong/Carnalitas#23]
**Describe the bug**
For some reason, futa traits seems to be applied to males

**To Reproduce**
1. Start a game with historical futa name, and futa inheritence enabled as well as futa content to common or very common
2. Wait a few days
3. Search for characters with the futa trait in the character finder

**Expected behavior**
Only women should have the futa trait active

**Screenshots**
![ck3_3q1Lqc4DNf](https://user-images.githubusercontent.com/5974879/92614647-9113f880-f2bc-11ea-9512-215400db4066.jpg)

**Game Version**
1.0.3

**Mods (List your mods, preferably with the load order they have in your launcher, as well as their version)**
1. Carnalitas 1.0.1

**Additional context**
Tested with the french version

**Comment by cherisong** [comment]
fixed
