### ISSUE TITLE
Courtiers inherit "wrong" trait

### ISSUE THREAD

**Issue by Luis276** [cherisong/Carnalitas#27]
**Describe the bug**
Whenever a courtier with a positive trait has a children, when that child becomes an adult it inherits a negative version of the trait, to be more specific the child inherits the XXXX_small_1 version of their parents trait.

**To Reproduce**
1. Open a new game and play in observer mode
2. Wait for 80 - 100 years to pass
3. In the character finder search for courtiers with positive traits and look at their children traits.

**Expected behavior**
It is expected to have children inherit a positive version when their parents have it or at least not inherit the XXX_small_1 version of said trait.

**Screenshots**

**Game Version**
CK3 1.0.3
Carnalitas 1.0.1

**Mods (List your mods, preferably with the load order they have in your launcher, as well as their version)**
1. Carnalitas
2. Free Console Access

**Additional context**
Here is an histogram with courtiers trait composition in one of my test runs (~120 years)
![image](https://user-images.githubusercontent.com/26292014/92627763-71b3a600-f291-11ea-852b-cb7002936ae6.png)

**Comment by cherisong** [comment]
fixed with latest update

the problem was that make_trait_inactive doesn't check whether the character actually has the trait before applying the inactive trait, causing all newborn children to get inactive dick_small_1 and tits_small_1
