### ISSUE TITLE
Change "stress from arousal" notification type

### ISSUE THREAD

**Issue by Triskelia** [cherisong/Carnalitas#32]
**Is your feature request related to a problem? Please describe.**
When you have a lot of notifications, it's easy to miss the "gain stress from arousal" notification

**Describe the solution you'd like**
I was thinking about changing the notification type to a toast notification (the one with a shield and scroll).

**Describe alternatives you've considered**
An alternative would be to make a custom icon for the notification, so it's at least easier to notice.

**Comment by it-thatlikeswarmdrinks** [comment]
Personally, I would find a toast to be a bit too obtrusive for a relatively minor effect. Would changing the notification style to something like `event_generic_bad` help?

**Comment by cherisong** [comment]
I think small notification is fine, it's not that important of an effect and we don't want to clutter the UI

**Comment by Triskelia** [comment]
Giving the notification a red background would make more sense indeed, since it's a bad event. 
What about changing its icon tho? I was thinking about using the gain stress icon, but with a pink arrow. But we could also just use the vanilla stress icon actually, since it's basically just a stress gain
