### ISSUE TITLE
Add a Fame trait for Slave Owners

### ISSUE THREAD

**Issue by DragonRB** [cherisong/Carnalitas#35]
**Assumptions**
Imprisonment reasons given to rulers are handled via opinion modifiers. Looking at the examples currently in game (Adultery/Fornication, Deviancy, Homosexuality), all of them have an associated trait that is used to deliver the opinion modifier, and thus an imprisonment reason if the behavior is illegal in the ruler's religion.

**Problem**
Currently there is no trait for Slave Owner listed in the roadmap for slavery. Without at least one such trait, it will be difficult or impossible to create religious doctrines for the state of slavery (illegal/shunned/accepted) using Paradox's methodology.

**Solution**
At least one slave owner trait would be needed to solve this problem. Ideally, in order to meet the stated goals of the religion task (specifically Same Religion Slavery vs. Different Religion Slavery) two traits would be created, one for each type.

**Additional Benefits**
The traits could be structured near-identically to Adulterer or Fornicator, making development theoretically easier. The traits could also be used in future enhancements as secrets, allowing hooks to be generated for/by slave owners and their peers and events around secret slaves.

**Comment by Triskelia** [comment]
Should be covered by #48 
- 2 new slave owner traits
- Ability for liege to ask vassal slave owner to free their slave, gives a reason to imprison if they refuse
