### ISSUE TITLE
Make breast size traits only affect size, not bust_clothes

### ISSUE THREAD

**Issue by cherisong** [cherisong/Carnalitas#42]
**Is your feature request related to a problem? Please describe.**
As pointed out on the forum thread, bust size traits force all characters to use the bust_clothes bust shape.

**Describe the solution you'd like**
Have characters with different bust blendshapes that still vary in size.

**Comment by Ernie0013** [comment]
I fixed this one in https://github.com/cherisong/Carnalitas/pull/52
