### ISSUE TITLE
Errors in error.log with STDs disabled

### ISSUE THREAD

**Issue by AdroitWord** [cherisong/Carnalitas#49]
**Describe the bug**
While running STDs disabled in the game rules, the error.log file will contain many error messages of this sort:
```
[13:45:07][jomini_script_system.cpp:169]: Script system error!
  Error: Undefined event target 'disease_type_for_trigger'
  Script location: file:  file: events/health_events.txt line: 995; can_contract_disease_trigger line: 13
```

I think this is because of the carn_20_health_triggers_overwrite.txt file, the trigger_if block checks scope:disease_type_for_trigger before it is set, a few lines below.  Doesn't happen with the game rule at default because of the trigger_if limit.

**To Reproduce**
1. Disable STDs in game rules
2. Start the game as any ruler
3. Unpause
4. Check error.log

**Game Version**
1.0.3

**Mods (List your mods, preferably with the load order they have in your launcher, as well as their version)**
1. Carnalitas (only)

**Comment by it-thatlikeswarmdrinks** [comment]
Thanks for the tip. It should be fixed now.
