### ISSUE TITLE
New traits preventing ''Strenghten Bloodline'' decision from being used

### ISSUE THREAD

**Issue by sinitarus** [cherisong/Carnalitas#63]
Hello,

there's an issue when having any of the new traits (e.g. big tits) it is preventing a decision ''Strenghten Bloodline" from being used despite having the positive congenital traits only.

It seems the game is marking the new traits as ''bad'' even if that is not a case. :)

**Comment by Triskelia** [comment]
Should be fixed in the next version.
Big tits and dicks will be explicitly flagged as good
